package com.zh.zhxk.bean;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of course.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Course implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Long id;

	/** name. */
	private String name;

	/** score. */
	private Integer score;

	/** teacher. */
	private Teacher teacher;

	/** The set of users_course. */
	private Set<UsersCourse> usersCourseSet;

	/**
	 * Constructor.
	 */
	public Course() {
		this.usersCourseSet = new HashSet<UsersCourse>();
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the name.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the score.
	 * 
	 * @param score
	 *            score
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * Get the score.
	 * 
	 * @return score
	 */
	public Integer getScore() {
		return this.score;
	}

	/**
	 * Set the teacher.
	 * 
	 * @param teacher
	 *            teacher
	 */
	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	/**
	 * Get the teacher.
	 * 
	 * @return teacher
	 */
	public Teacher getTeacher() {
		return this.teacher;
	}

	/**
	 * Set the set of the users_course.
	 * 
	 * @param usersCourseSet
	 *            The set of users_course
	 */
	public void setUsersCourseSet(Set<UsersCourse> usersCourseSet) {
		this.usersCourseSet = usersCourseSet;
	}

	/**
	 * Add the users_course.
	 * 
	 * @param usersCourse
	 *            users_course
	 */
	public void addUsersCourse(UsersCourse usersCourse) {
		this.usersCourseSet.add(usersCourse);
	}

	/**
	 * Get the set of the users_course.
	 * 
	 * @return The set of users_course
	 */
	public Set<UsersCourse> getUsersCourseSet() {
		return this.usersCourseSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Course other = (Course) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
