package com.zh.zhxk.bean;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of users.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Users implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Long id;

	/** name. */
	private String name;

	/** password. */
	private String password;

	/** realname. */
	private String realname;

	/** age. */
	private Integer age;

	/** sex. */
	private String sex;

	/** email. */
	private String email;

	/** dtype. */
	private String dtype;

	/** The set of users_course. */
	private Set<UsersCourse> usersCourseSet;

	/**
	 * Constructor.
	 */
	public Users() {
		this.usersCourseSet = new HashSet<UsersCourse>();
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the name.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the password.
	 * 
	 * @param password
	 *            password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the password.
	 * 
	 * @return password
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the realname.
	 * 
	 * @param realname
	 *            realname
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	/**
	 * Get the realname.
	 * 
	 * @return realname
	 */
	public String getRealname() {
		return this.realname;
	}

	/**
	 * Set the age.
	 * 
	 * @param age
	 *            age
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * Get the age.
	 * 
	 * @return age
	 */
	public Integer getAge() {
		return this.age;
	}

	/**
	 * Set the sex.
	 * 
	 * @param sex
	 *            sex
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * Get the sex.
	 * 
	 * @return sex
	 */
	public String getSex() {
		return this.sex;
	}

	/**
	 * Set the email.
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the email.
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the dtype.
	 * 
	 * @param dtype
	 *            dtype
	 */
	public void setDtype(String dtype) {
		this.dtype = dtype;
	}

	/**
	 * Get the dtype.
	 * 
	 * @return dtype
	 */
	public String getDtype() {
		return this.dtype;
	}

	/**
	 * Set the set of the users_course.
	 * 
	 * @param usersCourseSet
	 *            The set of users_course
	 */
	public void setUsersCourseSet(Set<UsersCourse> usersCourseSet) {
		this.usersCourseSet = usersCourseSet;
	}

	/**
	 * Add the users_course.
	 * 
	 * @param usersCourse
	 *            users_course
	 */
	public void addUsersCourse(UsersCourse usersCourse) {
		this.usersCourseSet.add(usersCourse);
	}

	/**
	 * Get the set of the users_course.
	 * 
	 * @return The set of users_course
	 */
	public Set<UsersCourse> getUsersCourseSet() {
		return this.usersCourseSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Users other = (Users) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
